
class Status:
    GET_INFOR = 0
    START_GET_INFO = 1
    DONE_GET_INFO = 2
    START_DOWNLOAD_ONE_VIDEO = 3
    DONE_DOWNLOAD_ONE_VIDEO = 4
    START_DOWNLOAD_LIST_VIDEO = 5
    DONE_DOWNLOAD_LIST_VIDEO = 6