# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\develop\python\DownloadAllMedia\ui\dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(730, 462)
        Form.setStyleSheet("#Form{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QProgressBar {\n"
"    border: 2px solid #2196F3; /* Viền màu xanh da trời */\n"
"    border-radius: 5px;\n"
"    background-color: #E3F2FD; /* Màu nền nhạt */\n"
"    text-align: center;\n"
"    font-weight: bold;\n"
"    color: black;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #2196F3; /* Màu xanh da trời */\n"
"    width: 10px;\n"
"}\n"
"\n"
"/* Nút \"Chạy ẩn\" */\n"
"#btnChayAn {\n"
"    background-color: #2196F3;\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"#btnChayAn:hover {\n"
"    background-color: #1976D2;\n"
"}\n"
"\n"
"/* Nút \"Hủy tải\" */\n"
"#btnHuyTai {\n"
"    background-color: #F44336;\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"#btnHuyTai:hover {\n"
"    background-color: #D32F2F;\n"
"}\n"
"\n"
"/* Nút \"Dừng\" */\n"
"#btnDung {\n"
"    background-color: #FFEB3B;\n"
"    color: black;\n"
"    border-radius: 5px;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"#btnDung:hover {\n"
"    background-color: #FBC02D;\n"
"}\n"
"")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setContentsMargins(30, 30, 30, 30)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalWidget = QtWidgets.QWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalWidget.sizePolicy().hasHeightForWidth())
        self.verticalWidget.setSizePolicy(sizePolicy)
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalWidget = QtWidgets.QWidget(self.verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalWidget.sizePolicy().hasHeightForWidth())
        self.horizontalWidget.setSizePolicy(sizePolicy)
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.horizontalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("d:\\develop\\python\\DownloadAllMedia\\ui\\img/TikTok.png"))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.horizontalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addWidget(self.horizontalWidget)
        self.verticalWidget_2 = QtWidgets.QWidget(self.verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalWidget_2.sizePolicy().hasHeightForWidth())
        self.verticalWidget_2.setSizePolicy(sizePolicy)
        self.verticalWidget_2.setObjectName("verticalWidget_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalWidget_2)
        self.verticalLayout_5.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.verticalWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.pbTienTrinh = QtWidgets.QProgressBar(self.verticalWidget_2)
        self.pbTienTrinh.setProperty("value", 24)
        self.pbTienTrinh.setObjectName("pbTienTrinh")
        self.verticalLayout_5.addWidget(self.pbTienTrinh)
        self.verticalLayout.addWidget(self.verticalWidget_2)
        self.verticalLayout_2.addWidget(self.verticalWidget)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.txtLog = QtWidgets.QTextEdit(Form)
        self.txtLog.setObjectName("txtLog")
        self.verticalLayout_3.addWidget(self.txtLog)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnDung = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnDung.setFont(font)
        self.btnDung.setObjectName("btnDung")
        self.horizontalLayout_3.addWidget(self.btnDung)
        self.btnHuyTai = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnHuyTai.setFont(font)
        self.btnHuyTai.setObjectName("btnHuyTai")
        self.horizontalLayout_3.addWidget(self.btnHuyTai)
        self.btnChayAn = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnChayAn.setFont(font)
        self.btnChayAn.setObjectName("btnChayAn")
        self.horizontalLayout_3.addWidget(self.btnChayAn)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "TIẾN TRÌNH TẢI"))
        self.label_3.setText(_translate("Form", "Đang tải: "))
        self.btnDung.setText(_translate("Form", "DỪNG"))
        self.btnHuyTai.setText(_translate("Form", "HỦY TẢI"))
        self.btnChayAn.setText(_translate("Form", "CHẠY ẨN"))
